jobs:
  deploy:
    name: EC2 deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend branch
        uses: actions/checkout@v3

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Run backend
        run: python3 app/main.py
        shell: bash
