name: EC2 deploy

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: EC2 deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend branch
        uses: actions/checkout@v3

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SOURCE: "backend/app/"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip3 install -r app/requirements.txt

      - run: python3 app/main.py

